name: HandleDumpParser
description: Tool to parse sourcemod handle dumps
homepage: https://hexer10.github.io/Sourcemod-HandleDumpParser/
author: Mattia <hexer504@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2
  pwa: ^0.2.0
  collection: ^1.14.12
  quiver: ^2.1.2+1
  csv: ^4.0.3
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.7.3
  build_web_compilers: ^2.9.0
  effective_dart: ^1.1.0